char *inititp =
"# -----------------------------------------------------------------------------\n"
"#   Initialisation script for offscreen command interpreter\n"
"#   Creates proc to take snapshot and record video\n"
"# -----------------------------------------------------------------------------\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Takes a picture of current frame\n"
"# -----------------------------------------------------------------------------\n"
"proc image {type fout col} {\n"
"    set w [width]\n"
"    set h [height]\n"
"    set pid [execbg ./grab-$type -s -w $w -h $h -o $fout]\n"
"    after 500\n"
"    colorspace $col\n"
"    kill add $pid\n"
"}\n"
"\n"
"proc png {fout} {\n"
"    image png $fout rgb\n"
"}\n"
"\n"
"proc jpeg {fout} {\n"
"    image jpeg $fout yuv\n"
"}\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Video recording\n"
"# -----------------------------------------------------------------------------\n"
"proc video {type fout nframes} {\n"
"    set w [width]\n"
"    set h [height]\n"
"    set fps [fps]\n"
"    set pid [execbg ./h264enc -s -w $w -h $h -n $nframes -f $fps  -o $fout --rcmode CBR]\n"
"    after 500\n"
"    colorspace yuv\n"
"    kill add $pid\n"
"}\n"
;
