char *inititp =
"# -----------------------------------------------------------------------------\n"
"#   Initialisation script for offscreen command interpreter\n"
"#   Creates proc to take snapshot and record video\n"
"# -----------------------------------------------------------------------------\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Takes a picture of current frame\n"
"# -----------------------------------------------------------------------------\n"
"proc image {type fout} {\n"
"    set w [width]\n"
"    set h [height]\n"
"    set pid [execbg ./image-$type -w $w -h $h -o $fout]\n"
"    kill add $pid\n"
"}\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Video recording\n"
"# -----------------------------------------------------------------------------\n"
"proc video {type fout nframes} {\n"
"    set w [width]\n"
"    set h [height]\n"
"    set pid [execbg ./video-$type -w $w -h $h -n $nframes -o $fout]\n"
"}\n"
;
