char *inititp =
"# -----------------------------------------------------------------------------\n"
"#   Initialisation script for offscreen command interpreter\n"
"#   Creates proc to take snapshot and record video\n"
"# -----------------------------------------------------------------------------\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Takes a picture of current frame\n"
"# -----------------------------------------------------------------------------\n"
"proc image {type fout col} {\n"
"    set w [width]\n"
"    set h [height]\n"
"    set pid [execbg ./grab-$type -s -w $w -h $h -o $fout]\n"
"    after 100\n"
"    colorspace $col\n"
"    kill add $pid\n"
"}\n"
"\n"
"proc png {fout} {\n"
"    image png $fout rgb\n"
"}\n"
"\n"
"proc jpeg {fout} {\n"
"    image jpeg $fout yuv\n"
"}\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Video recording\n"
"# -----------------------------------------------------------------------------\n"
"proc video {type fout nframes} {\n"
"    set w [width]\n"
"    set h [height]\n"
"    set fps [fps]\n"
"    set pid [execbg ./${type}enc -w $w -h $h -n $nframes -f $fps  -o $fout --rcmode CBR]\n"
"    after 200\n"
"    colorspace yuv\n"
"    kill add $pid\n"
"}\n"
"\n"
"proc h264 {fout nframes} {\n"
"   video h264 $fout $nframes\n"
"}\n"
"\n"
"proc h265 {fout nframes} {\n"
"   video h265 $fout $nframes\n"
"}\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Video streaming\n"
"# -----------------------------------------------------------------------------\n"
"proc h264stream {nframes} {\n"
"     execbg rm -f /tmp/h264fifo\n"
"     execbg mkfifo /tmp/h264fifo\n"
"     after 100\n"
"     \n"
"     h264 /tmp/h264fifo $nframes\n"
"\n"
"     puts {--------------------------------------------}\n"
"     puts {Note RTSP URL below to play stream}\n"
"     puts {--------------------------------------------}\n"
"     execbg ./h264streamer -s h264 -i /tmp/h264fifo\n"
"     puts {--------------------------------------------}\n"
"}\n"
"\n"
"# -----------------------------------------------------------------------------\n"
"#   Video streaming\n"
"# -----------------------------------------------------------------------------\n"
"proc h265stream {nframes} {\n"
"     execbg rm -f /tmp/h265fifo\n"
"     execbg mkfifo /tmp/h265fifo\n"
"     after 100\n"
"     \n"
"     h265 /tmp/h265fifo $nframes\n"
"\n"
"     puts {--------------------------------------------}\n"
"     puts {Note RTSP URL below to play stream}\n"
"     puts {--------------------------------------------}\n"
"     execbg ./h265streamer -s h265 -i /tmp/h265fifo\n"
"     puts {--------------------------------------------}\n"
"}\n"
;
